# tmux set
# source this conf need:
# 1. ctrl+prefix
# 2. :
# 3. source-file ~/.tmux.conf

# 设置加载在配置文件指令为：prefix + r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf is reloaded."

# Set the prefix to Ctrl+a
set -g prefix C-a
# unbind the prefix
unbind C-b
# enable mouse
set-option -g mouse on
# default statusbar colors

# 设置状态栏
set -g status on
set -g status-interval 20
set -g status-justify left
set -g status-keys vi
set -g status-left "#[fg=brightblue][#S]"
set -g status-left-length 20
set -g status-left-style default
set -g status-position bottom
set -g status-right "#{=21:pane_title}#[fg=brightblue]%H:%M %y-%m-%d"
set -g status-right-length 40
setw -g monitor-activity on
setw -g window-status-format '#[fg=brightblue] #I #W '
setw -g window-status-current-format '#[fg=magenta,bold] #I #W:#F'
setw -g window-status-activity-style bg=black
setw -g window-status-bell-style bg=black
set -g base-index 1 # 设置窗口的起始下标为1
set -g pane-base-index 1 # 设置面板的起始下标为1

setw -g automatic-rename on
set -g renumber-windows on

set -g set-titles on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# 自动备份时间间隔默认15min
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

run '~/.tmux/plugins/tpm/tpm'
